# Generated by Django 5.0.2 on 2024-04-15 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="today",
            field=models.DateTimeField(default=datetime.date(2024, 4, 15)),
        ),
    ]
